kind: pipeline
name: default

workspace:
  base: /go
  path: src/github.com/asobrien/ghedgetrim

steps:
- name: test
  image: golang
  commands:
  - env | sort
  - pwd
  - go get golang.org/x/lint/golint
  - go get -u github.com/golang/dep/cmd/dep
  - dep ensure
  - go build -v
  - make test
