---
language: go
sudo: false
notifications:
  email: true
go:
  - 1.6
  - 1.7
  - 1.8
  - 1.9
  - tip
env:
  global:
    - GO15VENDOREXPERIMENT=1
install:
  - go get github.com/golang/lint/golint
script:
  - go build -v
  - go vet $(go list ./... | grep -v vendor)
  - test -z "$(golint ./... | grep -v vendor | tee /dev/stderr)"
  - test -z "$(gofmt -s -l . | grep -v vendor | tee /dev/stderr)"
  - go test $(go list ./... | grep -v vendor)
before_deploy:
  - go get github.com/mitchellh/gox
  - make release
deploy:
  provider: releases
  api_key:
    secure: "O6nIrtN6b0OlVRQDTB6ZZWlLlZzKdZ5bVUjtiWVA6ZgB/uR/nbKWxCK60GXYgDraYsdNXa0Thw7ZR17q+LgLXVG6QpMxeZe5/a5fvQFMGPVsxmouZc0hCv1DtYM3kgT52hTF7JU8TE/9PmSTKuR5ltm0Db8RyTOAbSQRBRApvG85PsorarA3O9aQL5FIL2AR1l+DDP7dTput/Mms/+q+QE1aPfTGapMLHDQ/lLuaEG9qWLmsxy8ykyOtgMzfY5TD7g2Zw5E3CyL1mSbaW1DElVKzpTQRV7Mz7diOYdafPU3FcrTRK5XEjZXA69mpmK2LN2GyItjdrU0ndAUhhNP6mwaH5KsfLyuXsykRPQ+nglwVE4+rTgRKUGsKwQxZLAqgHAA2hq3tElHrTHwrDpSmtFdjEtC4Pbzlta+sl9xXhpe0JCFI7pxit1vxHSJEs6mWGARIEI2RrKy4jml+jHNLYjJBvW7hvxxtg85iCbSKscbnHLTz4JulQg76UHEZQ6aRPO2n8NcrngdQA5mjMPO6piN4Lm90B3q076s8DU5PlI0fySO6p55XK8vKUJ8C0orysgU6hV6zj07lIsN8a2XPpbcB2FFKQreLeoacjomxyaJJrQBbxfeziwP1SUkEpBqKvN0rPs0kG3ldwxBOj/BpILJ17aNRtZKuZBAPn6UKCHw="
  file_glob: true
  file:
    - build/*
  skip_cleanup: true
  on:
    go: tip
    tags: true